on:
  push:
    tags:        
      - 'v*'     
      
name: Build and push the tagged build to production

env:
  ENVIRONMENT_NAME: sergioaks
  RG: sergioaksrg

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{secrets.ACR_HOSTNAME}}/hello-python
          tags: |
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_HOSTNAME }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push production images
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          push: true

  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image

    steps:
      - uses: actions/checkout@v2

      - name: Get AKS Credentials
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ env.RG }}
          cluster-name: ${{ env.ENVIRONMENT_NAME }}

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          strategy: basic
          manifests: |
            deployment.yaml
          images: |
            ${{secrets.ACR_HOSTNAME}}/hello-python:${{ steps.build_push_image.meta.outputs.tags }}

