on: [push]
name: Build container

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.ACR_HOSTNAME }}
            username: ${{ secrets.ACR_USER }}
            password: ${{ secrets.ACR_PASSWORD }}
        - run: |
            docker build docker/Dockerfile -t ${{ secrets.ACR_HOSTNAME }}/hello-python:${{ github.sha }}
            docker push       ${{ secrets.ACR_HOSTNAME }}/hello-python:${{ github.sha }}
