name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_HOSTNAME }}
        password: ${{ secrets.ACR_USER }}
        login-server: ${{ secrets.ACR_PASSWORD }}
    
    - run: |
    docker build . -t ${{ secrets.ACR_HOSTNAME }}/hello-python:latest
    docker push ${{ secrets.ACR_HOSTNAME }}/hello-python:latest
